### ISSUE TITLE
support RADIUS protocal

### ISSUE THREAD

**Issue by lordk911** [aboutsip/pkts#131]
will pkts support parse RADIUS protocal?

**Comment by jonbo372** [comment]
Hi,

I have no plans myself to add radius. Note that I have Diameter as part of my https://github.com/sniceio/snice-codecs project and since the two are related, perhaps you could use some of that to build Radius framers/parsers. In short, pull requests are welcomed! 

I am planning to move all Layer 7 protocols into my `snice-codecs` library (really only SIP) to separate out pure pcaps related concerns with those of application layer.
