### ISSUE TITLE
package io.pkts.packet.sip two times existent

### ISSUE THREAD

**Issue by thaeger71** [aboutsip/pkts#50]
Hi,

I had an issue with packets including the keyword "NOTIFY". Even though it was not a SIP packet, the function SipParser.couldBeSipMessage() caused an exception in SipInitalLine.parse(). The exception occured in a catch method (line 99) which calls method SipParseException.getErrorOffset(). The exception was "NoSuchMethodError" ... and I wondered why, because the method is existent in repository pkts-sip in class io.pkts.packet.sip.SipParseExtension.
After a while I found the reason for this exception, my project, it's a springboot project, includes the pkts-core and pkts-sip repository, because I primary want to parse pcap data for SIP messages. And I found package io.pkts.packt.sip in both repositories....
I guess that the package in pkts-core is old and discontinued isn't it ?

**Comment by jonbo372** [comment]
I believe you are referring to the fact that SipParseException existed in two modules and in the same java package? If so, then yes, it was a mistake on my part that I missed. It was also reported as Issue #27. I simply renamed one of the exceptions since they weren't quite the same thing. Shouldn't have been the same packet from the beginning and then it would have been fine. Always an issue when you e.g. do shaded jars.
