### ISSUE TITLE
Error: package doesn not exist

### ISSUE THREAD

**Issue by Srinithi-B** [aboutsip/pkts#93]
I am trying to create a maven project using netbeans IDE. my import io.pkts statement are errors. What should i do??

**Comment by aboutsip** [comment]
Hi, that's odd. Sounds like you haven't managed to import it properly. If you just focus on making sure that maven is setup properly first, then I'm sure Netbeans would work (I don't use Netbeans myself - I use Eclipse & IntelliJ). So, if you just do a mvn install on your project from the command line, does that work? If no, you will have to fix that first. I'm guessing you haven't setup the dependency management correctly.

/Jonas

**Comment by Srinithi-B** [comment]
I am unable to follow it. Can you help me out with eclipse???

Srinithi Rengarajan

**Comment by aboutsip** [comment]
Hi again,

It sounds like you need to do some research on maven and whatever your favorite IDE is. I would start trying to understand maven and there are great resources on maven.apache.org. Also, I'm sure Netbeans have great maven integration as well so no need to swap to Eclipse just because of that.

I'm going to close this ticket since it seems to have nothing to do with pkts.io per se
